project:
  type: default

execute:
  freeze: auto
  cache: true
  echo: false
  warning: false
  error: true

format:

  html:
    theme:
      light: cosmo
      dark: darkly

    toc: true
    toc-depth: 3
    toc-location: left

    code-fold: true
    code-summary: "Python-Code anzeigen"

    code-tools: true
    smooth-scroll: true

    embed-resources: true

    number-sections: true

    fig-align: center
    fig-width: 8
    fig-height: 6

  pdf:
    documentclass: article

    papersize: a4

    fontsize: 11pt

    geometry:
      - margin=2.5cm

    number-sections: true

    colorlinks: true

    fig-align: center

    fig-width: 8
    fig-height: 6

jupyter: python3
